Update build-and-deploy.yml

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -82,9 +82,8 @@ jobs:
               echo "Validating attach IPA request: Does build create an IPA?"
               if [ "${{ inputs.job-type }}" != "Build IPA" ] && [ "${{ inputs.job-type }}" != "Deployment" ]; then
                 echo "Should Fail Build"
-                # (inputs.job-type == 'Build IPA'|| inputs.job-type == 'Deployment')
-                # echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
-                # exit 1
+                echo "::error file={Inputs Validation},line={1},endLine={1},title={Inputs Validation}::{Attach IPA requested but job type does not create an IPA}"
+                exit 1
               else
                 echo "Request to attach IPA is valid"
               fi
