Composite build mods (#5)
* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

* Update build-and-deploy.yml

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -12,6 +12,13 @@ on:
         description: 'Build Name'
         # Default value if no value is explicitly provided
         default: 'Memory Matrix'     
+
+
+      build-using-composite-action:
+        type: boolean
+        description: Build Via Composite Action
+        default: true
+        
       job-type:
         type: choice
         description: Job Type
@@ -34,7 +41,7 @@ on:
         description: Run Workflow Size Checks
       runner:
         type: choice
-        description: Job Type
+        description: Tools Version
         options:
         - "14"        
         - "15"           
@@ -65,12 +72,43 @@ jobs:
         run: |          
           echo "Starting Runner..."  
           ./scripts/start-runner.sh -b "${newBuildNumber}" -v "$appVersion"
+
+  inputs-validation:
+    runs-on: ["self-hosted", "x${{inputs.runner}}"]
+    steps:
+      - name: Inputs Validation
+        run: |
+            echo "Validating Inputs..."  
+            if ${{ inputs.attach-ipa }} == "true"; then
+              echo "Validating attach IPA request: Does build create an IPA?"
+              if [ "${{ inputs.job-type }}" != "Build IPA" ] && [ "${{ inputs.job-type }}" != "Deployment" ]; then
+                echo "::error file={Inputs Validation},line={1},endLine={1},title={Inputs Validation}::{Attach IPA requested but job type does not create an IPA}"
+                exit 1
+              fi
+            fi
+
+  build-via-composite-action:
+    if: inputs.build-using-composite-action == true 
+    needs: [inputs-validation]
+    runs-on: ["self-hosted", "x${{inputs.runner}}"]
+    steps:
+      - uses: actions/checkout@main
+      - id: build-via-composite-action-step
+        name: Build Via Composition
+        uses: rzmudzin/phx-build-deploy-action@main
+        with:
+          secrets: ${{ toJSON(secrets) }}
+          actionInputs: ${{ toJSON(inputs) }}
+          is-enterprise-app-build: inputs.enterprise-app
+          enable-extended-ops: false
+      - name: Build Summary
+        run: |
+            echo "Build Number ${newBuildNumber} Completed"
      
   build:
-    # The type of runner that the job will run on
+    if: inputs.build-using-composite-action != true 
+    needs: [inputs-validation]
     runs-on: ["self-hosted", "x${{inputs.runner}}"]
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       - name: Calculate New Build Number
         run: |
