Update build-and-deploy.yml

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -80,6 +80,8 @@ jobs:
             echo "Validating Inputs..."  
             if ${{ inputs.attach-ipa }} == "true"; then
               echo "Validating attach IPA request: Does build create an IPA?"
+              # echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
+              # exit 1
             fi
 
   build-via-composite-action:
